name: Update Toffee Playlist

on:
  schedule:
    - cron: '0 */4 * * *' # ржкрзНрж░рждрж┐ рзк ржШржгрзНржЯрж╛ржпрж╝ ржЪрж╛рж▓рж╛ржирзЛ рж╣ржмрзЗ
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: рж░рж┐ржкрзЛржЬрж┐ржЯрж░рж┐ ржХрзНрж▓рзЛржи ржХрж░рзБржи
        uses: actions/checkout@v2

      - name: ржкрж╛ржЗржержи рж╕рзЗржЯржЖржк ржХрж░рзБржи
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: ржирж┐рж░рзНржнрж░рждрж╛ ржЗржирж╕рзНржЯрж▓ ржХрж░рзБржи
        run: |
          pip install -r requirements.txt

      - name: рж╕рзНржХрзНрж░рж┐ржкрзНржЯ ржЪрж╛рж▓рж╛ржи
        run: python main.py

      - name: ржкрж░рж┐ржмрж░рзНрждржиржЧрзБрж▓рж┐ ржХржорж┐ржЯ ржХрж░рзБржи
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add toffee_playlist.m3u
          git diff --cached --quiet || git commit -m "ЁЯОп Auto-updated Toffee playlist with latest cookie"

      - name: ржкрж░рж┐ржмрж░рзНрждржиржЧрзБрж▓рж┐ ржкрзБрж╢ ржХрж░рзБржи
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
